services:
  client:
    build:
      context: ./client
    ports:
      - "5173:5173" # expose vite ke host
    volumes:
      - ./client:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - server

  server:
    build:
      context: ./server
    ports:
      - "5000:5000" # expose express api ke host
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npm run dev
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/donutmoo
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: donutmoo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
